services:
  # Combined Frontend + Backend Service
  - type: web
    name: todo-app
    env: python
    buildCommand: |
      echo "Building frontend..."
      cd frontend && npm install && npm run build
      echo "Installing backend dependencies..."
      cd ../backend && pip install -r requirements.txt
      echo "Build completed successfully!"
    startCommand: "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString

databases:
  - name: todo-db
    databaseName: todoapp
    user: todouser
