services:
  # Backend API
  - type: web
    name: todo-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: todo-db
          property: connectionString

  # Frontend
  - type: web
    name: todo-frontend
    env: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npx serve -s build -l $PORT"
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: todo-backend
          property: host

databases:
  - name: todo-db
    databaseName: todoapp
    user: todouser
