#!/usr/bin/env python3
"""
Google OAuth Setup Script for Todo App
This script helps you configure Google OAuth credentials
"""

import os
import sys

def create_env_files():
    """Create environment files with user input"""
    
    print("🔧 Google OAuth Setup for Todo App")
    print("=" * 50)
    print()
    
    # Get Google OAuth credentials from user
    print("📋 Please provide your Google OAuth credentials:")
    print("   (Get these from https://console.cloud.google.com/)")
    print()
    
    client_id = input("🔑 Enter your Google Client ID: ").strip()
    if not client_id:
        print("❌ Client ID is required!")
        return False
    
    client_secret = input("🔐 Enter your Google Client Secret: ").strip()
    if not client_secret:
        print("❌ Client Secret is required!")
        return False
    
    # Generate JWT secret
    import secrets
    jwt_secret = secrets.token_urlsafe(32)
    
    # Create backend .env file
    backend_env = f"""# Backend Environment Variables
# Generated by setup_google_oauth.py

# Google OAuth Configuration
GOOGLE_CLIENT_ID={client_id}
GOOGLE_CLIENT_SECRET={client_secret}

# JWT Configuration
JWT_SECRET_KEY={jwt_secret}

# Flask Configuration
FLASK_ENV=development
FLASK_DEBUG=True
"""
    
    # Create frontend .env file
    frontend_env = f"""# Frontend Environment Variables
# Generated by setup_google_oauth.py

# Google OAuth Configuration
REACT_APP_GOOGLE_CLIENT_ID={client_id}

# API Configuration
REACT_APP_API_URL=http://localhost:5000

# Other Configuration
GENERATE_SOURCEMAP=false
"""
    
    # Write files
    try:
        with open('backend/.env', 'w') as f:
            f.write(backend_env)
        
        with open('frontend/.env', 'w') as f:
            f.write(frontend_env)
        
        print()
        print("✅ Environment files created successfully!")
        print("   📁 backend/.env")
        print("   📁 frontend/.env")
        print()
        print("🚀 Next steps:")
        print("   1. Restart the backend server")
        print("   2. Restart the frontend server")
        print("   3. Test Google OAuth login at http://localhost:3000")
        print()
        return True
        
    except Exception as e:
        print(f"❌ Error creating environment files: {e}")
        return False

def main():
    """Main setup function"""
    
    # Check if we're in the right directory
    if not os.path.exists('backend') or not os.path.exists('frontend'):
        print("❌ Please run this script from the TO-DO_LIST directory")
        print("   Current directory should contain 'backend' and 'frontend' folders")
        return
    
    # Check if .env files already exist
    if os.path.exists('backend/.env') or os.path.exists('frontend/.env'):
        print("⚠️  Environment files already exist!")
        overwrite = input("   Do you want to overwrite them? (y/N): ").strip().lower()
        if overwrite != 'y':
            print("   Setup cancelled.")
            return
    
    # Create environment files
    if create_env_files():
        print("🎉 Google OAuth setup completed!")
    else:
        print("❌ Setup failed!")

if __name__ == "__main__":
    main()
